=== bongshell16/labprog/XML/Eventschema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
 targetNamespace="http://www.example.org/Eventschema"
  xmlns:tns="http://www.example.org/Eventschema" elementFormDefault="qualified">
  
  <complexType name="Eventtype">
  <sequence>
  <element name="Event" type="tns:eventtype" maxOccurs="20" minOccurs="1"></element>
  </sequence>
  </complexType>
  
  <complexType name="eventtype">
  <sequence>
  <element name="Eventname" type="string"></element>
  <element name="Eventvenue" type="string"></element>
  <element name="EventArtist"  type="string"></element> 
  <element name="Eventfees"  type="tns:mySal"></element> 
  </sequence>
  
  <attribute name="eid" type="ID" use="required"> </attribute>
  
  </complexType>
  
  <element name="globalevent" type="tns:Eventtype"></element>
  
  <simpleType name="mySal">
  <restriction base="integer">
  <minInclusive value="1000"></minInclusive>
  </restriction>
  </simpleType>
  
</schema>

=== bongshell16/labprog/XML/NewEvent.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:globalevent xmlns:tns="http://www.example.org/Eventschema" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.example.org/Eventschema Eventschema.xsd ">
  <tns:Event eid="E1">
    <tns:Eventname>Sunburn Goa</tns:Eventname>
    <tns:Eventvenue>Vagator</tns:Eventvenue>
    <tns:EventArtist>Nucleya</tns:EventArtist>
    <tns:Eventfees>10000</tns:Eventfees>
  </tns:Event>
  
  <tns:Event eid="E2">
    <tns:Eventname>Alan Walker Concert </tns:Eventname>
    <tns:Eventvenue>Delhi</tns:Eventvenue>
    <tns:EventArtist>Alan Walker</tns:EventArtist>
    <tns:Eventfees>15000</tns:Eventfees>
  </tns:Event>
  
  <tns:Event eid="E3">
    <tns:Eventname>Bollywood Concert</tns:Eventname>
    <tns:Eventvenue>Bangalore</tns:Eventvenue>
    <tns:EventArtist>Arman Malik</tns:EventArtist>
    <tns:Eventfees>12000</tns:Eventfees>
  </tns:Event>
  
  <tns:Event eid="E4">
   <tns:Eventname>SUNBURN ARENA WITH DJ SNAKE</tns:Eventname>
    <tns:Eventvenue>Bangalore</tns:Eventvenue>
    <tns:EventArtist>DJ Snake</tns:EventArtist>
    <tns:Eventfees>25000</tns:Eventfees>
  </tns:Event>
  
  <tns:Event eid="E5">
   <tns:Eventname>Lauv</tns:Eventname>
    <tns:Eventvenue>Mumbai</tns:Eventvenue>
    <tns:EventArtist>Lauv</tns:EventArtist>
    <tns:Eventfees>20000</tns:Eventfees>
  </tns:Event>
  
  <tns:Event eid="E6">
   <tns:Eventname>Neon East Fest</tns:Eventname>
    <tns:Eventvenue>Mumbai</tns:Eventvenue>
    <tns:EventArtist>MURA MASA, Mr. Carmack, Photay and KLLO</tns:EventArtist>
    <tns:Eventfees>30000</tns:Eventfees>
  </tns:Event>
</tns:globalevent>
