=== bongshell16/labprog/XML/Eventtype.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT Eventdetails (Event+)>
<!ELEMENT Event (Eventname,Eventvenue,EventArtist,Eventfees)>
<!ELEMENT Eventname (#PCDATA)>
<!ELEMENT Eventvenue (#PCDATA)>
<!ELEMENT EventArtist (#PCDATA)>
<!ELEMENT Eventfees (#PCDATA)>
<!ATTLIST Event eid ID #REQUIRED>

=== bongshell16/labprog/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Eventstyle.xsl"?>
<!DOCTYPE Eventdetails SYSTEM "Eventtype.dtd">
<Eventdetails>

 <Event eid="E1">
 <Eventname>Sunburn Goa</Eventname>
 <Eventvenue>Vagator</Eventvenue>
 <EventArtist>Nucleya</EventArtist>
 <Eventfees>10000</Eventfees>
 </Event>
 
 <Event eid="E2">
 <Eventname>Alan Walker Concert</Eventname>
 <Eventvenue>Delhi</Eventvenue>
 <EventArtist>Alan Walker</EventArtist>
  <Eventfees>15000</Eventfees>
 </Event>
 
  <Event eid="E3" >
  <Eventname>Bollywood Concert</Eventname>
  <Eventvenue>Bangalore</Eventvenue>
  <EventArtist>Arman Malik</EventArtist>
  <Eventfees>12000</Eventfees>
  </Event>
 
  <Event eid="E4">
  <Eventname>SUNBURN ARENA WITH DJ SNAKE</Eventname>
  <Eventvenue>Bangalore</Eventvenue>
  <EventArtist>DJ Snake</EventArtist>
  <Eventfees>25000</Eventfees>
  </Event>
  
  <Event eid="E5">
  <Eventname>Lauv</Eventname>
  <Eventvenue>Mumbai</Eventvenue>
  <EventArtist>Lauv</EventArtist>
  <Eventfees>20000</Eventfees>
  </Event>
  
  <Event eid="E6">
  <Eventname>Neon East Fest</Eventname>
  <Eventvenue>Bandra East,Mumbai</Eventvenue>
  <EventArtist>MURA MASA, Mr. Carmack, Photay and KLLO</EventArtist>
  <Eventfees>30000</Eventfees>
  </Event>


</Eventdetails>
